manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: c06fa48ce59e016105d79c20942d085314502d8d
      import: app/west.yml
